### PR TITLE
Attempts at minor Updates (comments updated)

### PR DESCRIPTION
**Pull request by imTURBObro**
my attempt is:

lottery - change the prefix to = and have it mention/ping winner in the notification channel.

skilling - reject this please I got NO CLUE what happened but those edits make no sense to me must have been accident.

usercommands - explain how joining your server gives extra loot.

wilderness - explains .pk info in more detail, and attempt to have it say the person's discord id name over their server nickname so it doesn't appear as "none" -- but now I saw that when a item or rare is pk'd off another person it mentions them both! I need to hunt that code line down and steal the mention/ping user code!

### CODE REVIEW

**Review by chris-porter-lexeau — CHANGES_REQUESTED** [review]
ctx.author.mention doesn't work here because the bot isn't replying to anyone -- there is no author

**Review by chris-porter-lexeau — APPROVED** [review]

**Review by chris-porter-lexeau — COMMENTED** [review]
This is really long -- please go back and comment the changes because in the difference sheet it looks like you're pasting all of slayer into here while removing prayer/herblore?

**Comment by imTURBObro** [comment]
see I'm learning. I really gotta learn more

**Review by imTURBObro — COMMENTED** [review]
my attempt was:

lottery - change the prefix to = and have it mention/ping winner in the notification channel.

skilling - reject this please I got NO CLUE what happened but those edits make no sense to me must have been accident.

usercommands - explain how joining your server gives extra loot.

wilderness - explains .pk info in more detail, and attempt to have it say the person's discord id name over their server nickname so it doesn't appear as "none" -- but now I saw that when a item or rare is pk'd off another person it mentions them both! I need to hunt that code line down and steal the mention/ping user code!

**Comment by imTURBObro** [comment]
> This is really long -- please go back and comment the changes because in the difference sheet it looks like you're pasting all of slayer into here while removing prayer/herblore?

huge mistake I had no clue that was even added to the request plz deny the skilling one

**Pull request merged**
