### PR TITLE
might have nickname to user id  code wrong

### PR DESCRIPTION
**Pull request by imTURBObro**

### CODE REVIEW

**Review by chris-porter-lexeau — APPROVED** [review]

**Review by chris-porter-lexeau — APPROVED** [review]

**Review by chris-porter-lexeau — CHANGES_REQUESTED** [review]
Is this an accidental copy paste into the store? file

**Review by chris-porter-lexeau — APPROVED** [review]
Looks good

**Review by chris-porter-lexeau — APPROVED** [review]
I think 100m is a good bump up. Nice work.

**Review by chris-porter-lexeau — APPROVED** [review]

**Review by chris-porter-lexeau — APPROVED** [review]

**Review by chris-porter-lexeau — APPROVED** [review]

**Review by chris-porter-lexeau — APPROVED** [review]

**Comment by imTURBObro** [comment]
yay

**Pull request merged**
